name: Semantic Version

on:
  pull_request:
    types: closed

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - name: Tag with semantic version
        uses: K-Phoen/semver-release-action@master
        with:
          release_branch: master
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}