name: Pre Merge CI

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize, reopened]
    branches:
      - master

jobs:
  label-check:
    runs-on: ubuntu-latest
    steps:
      - uses: yashhy/pr-label-check-and-comment-action@master
        with:
          required_labels: 'major, minor, patch'
          GITHUB_TOKEN: '${{ secrets.PERSONAL_ACCESS_TOKEN }}'
          
  update_release_draft:
    runs-on: ubuntu-latest
    needs: [label-check]
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "master"
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
