name: Demo Composite Actions

on: [push]

jobs:     
  use-a:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          repository: powers2537/composite-actions
      - name: Run Action A
        uses: ./.github/actions/action-a
        with:
          who-to-greet: "Mona the github Octocat"
      - name: Run Action B
        uses: ./.github/actions/action-b
        with:
          who-to-greet: "Santa Claus"
  use-b:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: powers2537/composite-actions
      - name: Run Action B
        uses: ./.github/actions/action-b
        with:
          who-to-greet: "Mario"
