name: Demo Composite Actions

on: [push]

jobs:     
  use-a:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: 'my-actions'
          repository: 'powers2537/compiste-actions'
      - uses: ./my-actions/.github/actions/action-a
        with:
          who-to-greet: "Mona the github Octocat"
