name: Demo Composite Actions

on: [push]

jobs:     
  use-a:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout Other Repo
        uses: actions/checkout@v2
        with:
          repository: 'powers2537/compiste-actions'
          path: my-actions 
      - name: List Files
        run: ls -la
#         uses: ./my-actions/.github/actions/action-a
#         with:
#           who-to-greet: "Mona the github Octocat"
