name: Demo Some Things

on:
  release:
    types: [released]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Set env var
        run: echo "GIT_TAG=${GITHUB_REF/refs\/tags\//}" >> $TAG
  
  job2:
    runs-on: ubuntu-latest
    needs: [job1]
    steps:
      - name: Echo Tag
        run: echo $TAG
        
