name: Demo Some Things

on:
  release:
    types: [released]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Echo event name
        run: echo ${{ github.event_name }}
      - name: Echo git_name env var
        run: echo $GITHUB_EVENT_NAME
